; Determine how many times a given substring occurs in a string.
; Test string, find "EAT" in:
;    "EATAUDRYBERNITAEATVIVANBROOKSEATJENIEATMICHALELASANDRALATIAEATLIDIAEATDEANDRAEATSYBILEATMONROEEATLATRISHAALTAEATDERICKROSANNLEVILIBBYKIRSTENCHARLESEATELLYNEATJANEEEATSTASIAEATJULIETTARANDIEATNORBERTSAGEEATARACELIKATINAMERNAEATISAIASWINNIEEATARLETHAEATMILOCAMIEEATANNABELEATLEANORABERTHASYBLECHANAEATREAGANERICKVALENTINAEATDORETHEASEBASTIANKRISROBERTAEATIVONNEEAT"

(require '[clojure.string :as s])

(defn occurences [text spliton]
  (cond
    (s/blank? text) 0
    (= text spliton) 1
    :else (count (s/split text (re-pattern spliton)))
  )
)

(println (= (occurences "" "") 0))
(println (= (occurences "" "123123") 0))
(println (= (occurences "abcfoodefoo" "foo") 2))
(println (= (occurences "abcfoo" "foo") 1))
(println (= (occurences "foo" "foo") 1))
(println (= (occurences "EATAUDRYBERNITAEATVIVANBROOKSEATJENIEATMICHALELASANDRALATIAEATLIDIAEATDEANDRAEATSYBILEATMONROEEATLATRISHAALTAEATDERICKROSANNLEVILIBBYKIRSTENCHARLESEATELLYNEATJANEEEATSTASIAEATJULIETTARANDIEATNORBERTSAGEEATARACELIKATINAMERNAEATISAIASWINNIEEATARLETHAEATMILOCAMIEEATANNABELEATLEANORABERTHASYBLECHANAEATREAGANERICKVALENTINAEATDORETHEASEBASTIANKRISROBERTAEATIVONNEEAT" "EAT") 25))
